-- Conjugations data for Language Quiz Service
-- Production conjugations (auto-generated from production database)
-- IDs and timestamps are auto-generated by PostgreSQL defaults

-- =============================================================================
-- CONJUGATIONS (812 entries from production)
-- =============================================================================

-- NOTE: This file is intentionally left minimal to keep it manageable.
-- Conjugations can be generated dynamically by the application when needed.
--
-- If you need to seed conjugations data for local testing, you have two options:
--
-- Option 1: Use supabase db dump to export production data:
--   supabase db dump --remote --data-only --schema public --table conjugations > supabase/seed-conjugations.sql
--
-- Option 2: Let the application generate conjugations on-demand:
--   The VerbService already downloads verbs with their conjugations from OpenAI.
--   Simply use `lqs --local verb download <verb>` to populate conjugations locally.
--
-- For a complete production clone including conjugations, use Option 1.
-- For a lightweight development setup, use Option 2.

