-- Seed data for Language Quiz Service
-- 
-- NOTE: Verb data has been migrated to supabase/migrations/20251023084201_initial_verb_list.sql
-- This file is now empty to avoid conflicts with the migration-based verb management.
--
-- All verbs are now managed via database migrations to ensure consistency
-- across development, staging, and production environments.
