# fly.toml app configuration file generated for language-quiz-app-staging on 2025-07-14T14:58:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'language-quiz-app-staging'
primary_region = 'ams'

[build]

[env]
  ENVIRONMENT = "staging"
  WEB_PORT = "8080"
  RATE_LIMIT_REQUESTS = "100"
  
  # OpenTelemetry Resource Attributes
  OTEL_SERVICE_NAME = "language-quiz-service"
  OTEL_SERVICE_NAMESPACE = "lqs"
  OTEL_DEPLOYMENT_ENVIRONMENT = "staging"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
