# OpenTelemetry Collector - Simple configuration
# Receives OTLP and exposes Prometheus metrics for scraping

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s

exporters:
  # Expose metrics in Prometheus format for scraping
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      environment: local
    
  # Log traces (drop them for now)
  logging:
    verbosity: detailed

service:
  telemetry:
    logs:
      level: info
  
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
