-- Migration: Initial Verb Conjugations
-- Created: 2025-10-24
-- Description: Loads 595 conjugations for 85 essential French verbs across 7 tenses
--
-- This migration pre-loads all conjugations to ensure consistent test data
-- and eliminate the need for API calls during application initialization.
--
-- IDEMPOTENCY:
-- This migration uses ON CONFLICT to upsert conjugations, making it safe to rerun.
-- The unique constraint is: (infinitive, auxiliary, reflexive, tense)
--
-- SOURCE: Generated from local Supabase database dump
-- Date: 2025-10-24
--
-- =============================================================================

INSERT INTO public.conjugations (infinitive, auxiliary, reflexive, tense, first_person_singular, second_person_singular, third_person_singular, first_person_plural, second_person_plural, third_person_plural)
VALUES
	('mourir', 'être', false, 'present', 'meurt', 'meurs', 'meurt', 'mourons', 'mourez', 'meurent'),
	('mourir', 'être', false, 'future_simple', 'mourrai', 'mourras', 'mourra', 'mourrons', 'mourrez', 'mourront'),
	('penser', 'avoir', false, 'conditionnel', 'penserais', 'penserais', 'penserait', 'penserions', 'penseriez', 'penseraient'),
	('chanter', 'avoir', false, 'present', 'chante', 'chantes', 'chante', 'chantons', 'chantez', 'chantent'),
	('pouvoir', 'avoir', false, 'present', 'peux', 'peux', 'peut', 'pouvons', 'pouvez', 'peuvent'),
	('ouvrir', 'avoir', false, 'subjonctif', 'ouvre', 'ouvres', 'ouvre', 'ouvrions', 'ouvriez', 'ouvrent'),
	('étudier', 'avoir', false, 'conditionnel', 'étudierais', 'étudierais', 'étudierait', 'étudierions', 'étudieriez', 'étudieraient'),
	('passer', 'être', false, 'present', 'passe', 'passes', 'passe', 'passons', 'passez', 'passent'),
	('partir', 'être', false, 'imparfait', 'partais', 'partais', 'partait', 'partions', 'partiez', 'partaient'),
	('parler', 'avoir', false, 'subjonctif', 'parle', 'parles', 'parle', 'parlions', 'parliez', 'parlent'),
	('expliquer', 'avoir', false, 'passe_compose', 'ai expliqué', 'as expliqué', 'a expliqué', 'avons expliqué', 'avez expliqué', 'ont expliqué'),
	('croire', 'avoir', false, 'present', 'crois', 'crois', 'croit', 'croyons', 'croyez', 'croient'),
	('comprendre', 'avoir', false, 'passe_compose', 'ai compris', 'as compris', 'a compris', 'avons compris', 'avez compris', 'ont compris'),
	('permettre', 'avoir', false, 'present', 'permets', 'permet', 'permet', 'permettons', 'permettez', 'permettent'),
	('croire', 'avoir', false, 'imparfait', 'croyais', 'croyais', 'croyait', 'croyions', 'croyiez', 'croyaient'),
	('permettre', 'avoir', false, 'passe_compose', 'ai permis', 'as permis', 'a permis', 'avons permis', 'avez permis', 'ont permis'),
	('boire', 'avoir', false, 'present', 'bois', 'bois', 'boit', 'buvons', 'buvez', 'boivent'),
	('montrer', 'avoir', false, 'imparfait', 'montrais', 'montrais', 'montrait', 'montrions', 'montriez', 'montraient'),
	('promettre', 'avoir', false, 'conditionnel', 'promettrais', 'promettrais', 'promettrait', 'promettrions', 'promettriez', 'promettraient'),
	('devoir', 'avoir', false, 'future_simple', 'devrai', 'devras', 'devra', 'devrons', 'devrez', 'devront'),
	('descendre', 'être', false, 'passe_compose', 'suis descendu', 'es descendu', 'est descendu', 'sommes descendus', 'êtes descendus', 'sont descendus'),
	('expliquer', 'avoir', false, 'imperatif', '', 'explique', '', 'expliquons', 'expliquez', ''),
	('promettre', 'avoir', false, 'subjonctif', 'que je promette', 'que tu promettes', 'qu''il/elle/on promette', 'que nous promettions', 'que vous promettiez', 'qu''ils/elles promettent'),
	('être', 'avoir', false, 'passe_compose', 'ai été', 'as été', 'a été', 'avons été', 'avez été', 'ont été'),
	('apprendre', 'avoir', false, 'subjonctif', 'apprenne', 'apprennes', 'apprenne', 'apprenions', 'appreniez', 'apprennent'),
	('décrire', 'avoir', false, 'imperatif', '', 'décris', '', 'décrivons', 'décrivez', ''),
	('jouer', 'avoir', false, 'present', 'joue', 'joues', 'joue', 'jouons', 'jouez', 'jouent'),
	('être', 'avoir', false, 'future_simple', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront'),
	('descendre', 'être', false, 'subjonctif', 'descende', 'descendes', 'descende', 'descendions', 'descendiez', 'descendent'),
	('monter', 'être', false, 'subjonctif', 'monte', 'montes', 'monte', 'montions', 'montiez', 'montent'),
	('entrer', 'être', false, 'subjonctif', 'entre', 'entres', 'entre', 'entrions', 'entriez', 'entrent'),
	('ressembler', 'avoir', false, 'passe_compose', 'ai ressemblé', 'as ressemblé', 'a ressemblé', 'avons ressemblé', 'avez ressemblé', 'ont ressemblé'),
	('ressembler', 'avoir', false, 'imperatif', '', 'ressemble', '', 'ressemblons', 'ressembtez', ''),
	('rire', 'avoir', false, 'passe_compose', 'ai ri', 'as ri', 'a ri', 'avons ri', 'avez ri', 'ont ri'),
	('rire', 'avoir', false, 'imperatif', '', 'ris', '', 'rions', 'riez', ''),
	('savoir', 'avoir', false, 'conditionnel', 'saurais', 'saurais', 'saurait', 'saurions', 'sauriez', 'sauraient'),
	('réfléchir', 'avoir', false, 'passe_compose', 'ai réfléchi', 'as réfléchi', 'a réfléchi', 'avons réfléchi', 'avez réfléchi', 'ont réfléchi'),
	('réfléchir', 'avoir', false, 'imperatif', '', 'réfléchis', '', 'réfléchissons', 'réfléchissez', ''),
	('retourner', 'être', false, 'passe_compose', 'suis retourné', 'es retourné', 'est retourné', 'sommes retournés', 'êtes retournés', 'sont retournés'),
	('retourner', 'être', false, 'imperatif', '', 'retourne', '', 'retournons', 'retournez', ''),
	('se lever', 'être', true, 'passe_compose', 'me suis levé(e)', 't''es levé(e)', 's''est levé(e)', 'nous sommes levé(e)s', 'vous êtes levé(e)s', 'se sont levé(e)s'),
	('s''arrêter', 'être', true, 'imparfait', 'm''arrêtais', 't''arrêtais', 's''arrêtait', 'nous arrêtions', 'vous arrêtiez', 's''arrêtaient'),
	('tenir', 'avoir', false, 'conditionnel', 'tiendrais', 'tiendrais', 'tiendrait', 'tiendrions', 'tiendriez', 'tiendraient'),
	('révéler', 'avoir', false, 'passe_compose', 'révélé', 'révélé', 'révélé', 'révélés', 'révélés', 'révélés'),
	('tomber', 'être', false, 'future_simple', 'tomberai', 'tomberas', 'tombera', 'tomberons', 'tomberez', 'tomberont'),
	('se promener', 'être', true, 'future_simple', 'me promènerai', 'te promèneras', 'se promènera', 'nous promènerons', 'vous promènerez', 'se promèneront'),
	('se coucher', 'être', true, 'future_simple', 'me coucherai', 'te coucheras', 'se couchera', 'nous coucherons', 'vous coucherez', 'se coucheront'),
	('sortir', 'être', false, 'imparfait', 'sortais', 'sortais', 'sortait', 'sortions', 'sortiez', 'sortaient'),
	('revenir', 'être', false, 'future_simple', 'reviendrai', 'reviendras', 'reviendra', 'reviendrons', 'reviendrez', 'reviendront'),
	('vendre', 'avoir', false, 'future_simple', 'vendrai', 'vendras', 'vendra', 'vendrons', 'vendrez', 'vendront'),
	('trouver', 'avoir', false, 'passe_compose', 'ai trouvé', 'as trouvé', 'a trouvé', 'avons trouvé', 'avez trouvé', 'ont trouvé'),
	('trouver', 'avoir', false, 'imperatif', '', 'trouve', '', 'trouvons', 'trouvez', ''),
	('servir', 'avoir', false, 'future_simple', 'servirai', 'serviras', 'servira', 'servirons', 'servirez', 'serviront'),
	('suivre', 'avoir', false, 'future_simple', ' suivrai', 'suivras', 'suivra', 'suivrons', 'suivrez', 'suivront'),
	('choisir', 'avoir', false, 'present', 'choisis', 'choisis', 'choisit', 'choisissons', 'choisissez', 'choisissent'),
	('courir', 'avoir', false, 'present', 'cours', 'cours', 'court', 'courons', 'courez', 'courent'),
	('penser', 'avoir', false, 'present', 'pense', 'penses', 'pense', 'pensons', 'pensez', 'pensent'),
	('choisir', 'avoir', false, 'passe_compose', 'ai choisi', 'as choisi', 'a choisi', 'avons choisi', 'avez choisi', 'ont choisi'),
	('penser', 'avoir', false, 'passe_compose', 'ai pensé', 'as pensé', 'a pensé', 'avons pensé', 'avez pensé', 'ont pensé'),
	('mourir', 'être', false, 'passe_compose', 'mort', 'mort', 'mort', 'morts', 'morts', 'morts'),
	('courir', 'avoir', false, 'passe_compose', 'ai couru', 'as couru', 'a couru', 'avons couru', 'avez couru', 'ont couru'),
	('choisir', 'avoir', false, 'imparfait', 'choisissais', 'choisissais', 'choisissait', 'choisissions', 'choisissiez', 'choisissaient'),
	('courir', 'avoir', false, 'imparfait', 'courais', 'courais', 'courait', 'courions', 'couriez', 'couraient'),
	('penser', 'avoir', false, 'imparfait', 'pensais', 'pensais', 'pensait', 'pensiez', 'pensiez', 'pensaient'),
	('mourir', 'être', false, 'imparfait', 'mourais', 'mourais', 'mourait', 'mourions', 'mouriez', 'mouraient'),
	('choisir', 'avoir', false, 'future_simple', 'choisirai', 'choiras', 'choisira', 'choisirons', 'choisirez', 'choisiront'),
	('courir', 'avoir', false, 'future_simple', 'courrai', 'courras', 'courra', 'courrons', 'courrez', 'courront'),
	('penser', 'avoir', false, 'future_simple', 'penserai', 'penseras', 'pensera', 'penserons', 'penserez', 'penseront'),
	('choisir', 'avoir', false, 'conditionnel', 'choisirais', 'choisirais', 'choisirait', 'choisirions', 'choisiriez', 'choisiraient'),
	('mourir', 'être', false, 'conditionnel', 'mourrais', 'mourrais', 'mourrait', 'mourrions', 'mourriez', 'mourraient'),
	('courir', 'avoir', false, 'conditionnel', 'courrais', 'courrais', 'courrait', 'courrions', 'courriez', 'courraient'),
	('choisir', 'avoir', false, 'subjonctif', 'choisisse', 'choisisses', 'choisisse', 'choisissions', 'choisissiez', 'choisissent'),
	('penser', 'avoir', false, 'subjonctif', 'pense', 'penses', 'pense', 'pensons', 'pensiez', 'pensent'),
	('mourir', 'être', false, 'subjonctif', 'meure', 'meures', 'meure', 'mourions', 'mouriez', 'meurent'),
	('courir', 'avoir', false, 'subjonctif', 'coures', 'coures', 'coures', 'courions', 'couriez', 'courent'),
	('choisir', 'avoir', false, 'imperatif', '', 'choisis', '', 'choisissons', 'choisissez', ''),
	('penser', 'avoir', false, 'imperatif', '', 'pense', '', 'pensons', 'pensez', ''),
	('courir', 'avoir', false, 'imperatif', '', 'cours', '', 'courons', 'courez', ''),
	('mourir', 'être', false, 'imperatif', '', 'meurs', '', 'mourons', 'mourez', ''),
	('perdre', 'avoir', false, 'present', 'perds', 'perds', 'perd', 'perdons', 'perdez', 'perdent'),
	('mettre', 'avoir', false, 'present', 'mets', 'mets', 'met', 'mettons', 'mettez', 'mettent'),
	('ouvrir', 'avoir', false, 'present', 'ouvre', 'ouvres', 'ouvre', 'ouvrons', 'ouvrez', 'ouvrent'),
	('avoir', 'avoir', false, 'present', 'ai', 'as', 'a', 'avons', 'avez', 'ont'),
	('mettre', 'avoir', false, 'passe_compose', 'ai mis', 'as mis', 'a mis', 'avons mis', 'avez mis', 'ont mis'),
	('perdre', 'avoir', false, 'passe_compose', 'ai perdu', 'as perdu', 'a perdu', 'avons perdu', 'avez perdu', 'ont perdu'),
	('ouvrir', 'avoir', false, 'passe_compose', 'ai ouvert', 'as ouvert', 'a ouvert', 'avons ouvert', 'avez ouvert', 'ont ouvert'),
	('chanter', 'avoir', false, 'passe_compose', 'ai chanté', 'as chanté', 'a chanté', 'avons chanté', 'avez chanté', 'ont chanté'),
	('avoir', 'avoir', false, 'passe_compose', 'eu', 'eu', 'eu', 'eu', 'eu', 'eu'),
	('mettre', 'avoir', false, 'imparfait', 'mettais', 'mettais', 'mettait', 'mettions', 'mettiez', 'mettaient'),
	('ouvrir', 'avoir', false, 'imparfait', 'ouvrais', 'ouvrais', 'ouvrait', 'ouvrions', 'ouvriez', 'ouvraient'),
	('chanter', 'avoir', false, 'imparfait', 'chantais', 'chantais', 'chantait', 'chantions', 'chantiez', 'chantaient'),
	('avoir', 'avoir', false, 'imparfait', 'avais', 'avais', 'avait', 'avions', 'aviez', 'avaient'),
	('perdre', 'avoir', false, 'imparfait', 'perdais', 'perdais', 'perdait', 'perdions', 'perdiez', 'perdaient'),
	('étudier', 'avoir', false, 'present', 'étudie', 'étudies', 'étudie', 'étudions', 'étudiez', 'étudient'),
	('naître', 'être', false, 'present', 'nais', 'nais', 'naît', 'naissons', 'naissez', 'naissent'),
	('mettre', 'avoir', false, 'future_simple', 'mettrai', 'mettras', 'mettra', 'mettrons', 'mettrez', 'mettront'),
	('chanter', 'avoir', false, 'future_simple', 'chanterai', 'chanteras', 'chantera', 'chanterons', 'chanterez', 'chanteront'),
	('ouvrir', 'avoir', false, 'future_simple', 'ouvrirai', 'ouvriras', 'ouvrira', 'ouvrirons', 'ouvrirez', 'ouvriront'),
	('perdre', 'avoir', false, 'future_simple', 'perdrai', 'perdras', 'perdra', 'perdrons', 'perdrez', 'perdront'),
	('avoir', 'avoir', false, 'future_simple', 'aurai', 'auras', 'aura', 'aurons', 'aurez', 'auront'),
	('aller', 'être', false, 'present', 'vais', 'vas', 'va', 'allons', 'allez', 'vont'),
	('finir', 'avoir', false, 'present', 'finis', 'finis', 'finit', 'finissons', 'finissez', 'finissent'),
	('demander', 'avoir', false, 'present', 'demande', 'demandes', 'demande', 'demandons', 'demandez', 'demandent'),
	('étudier', 'avoir', false, 'passe_compose', 'ai étudié', 'as étudié', 'a étudié', 'avons étudié', 'avez étudié', 'ont étudié'),
	('naître', 'être', false, 'passe_compose', 'suis né', 'es né', 'est né', 'sommes nés', 'êtes nés', 'sont nés'),
	('chanter', 'avoir', false, 'conditionnel', 'chanterais', 'chanterais', 'chanterait', 'chanterions', 'chanteriez', 'chanteraient'),
	('mettre', 'avoir', false, 'conditionnel', 'mettrais', 'mettrais', 'mettrait', 'mettrions', 'mettriez', 'mettraient'),
	('perdre', 'avoir', false, 'conditionnel', 'perdrais', 'perdrais', 'perdrait', 'perdrions', 'perdriez', 'perdraient'),
	('ouvrir', 'avoir', false, 'conditionnel', 'ouvrirais', 'ouvrirais', 'ouvrirait', 'ouvririons', 'ouvririez', 'ouvriraient'),
	('avoir', 'avoir', false, 'conditionnel', 'aurais', 'aurais', 'aurait', 'aurions', 'auriez', 'auraient'),
	('aller', 'être', false, 'passe_compose', 'suis allé', 'es allé', 'est allé', 'sommes allés', 'êtes allés', 'sont allés'),
	('parler', 'avoir', false, 'present', 'parle', 'parles', 'parle', 'parlons', 'parlez', 'parlent'),
	('finir', 'avoir', false, 'passe_compose', 'ai fini', 'as fini', 'a fini', 'avons fini', 'avez fini', 'ont fini'),
	('demander', 'avoir', false, 'passe_compose', 'ai demandé', 'as demandé', 'a demandé', 'avons demandé', 'avez demandé', 'ont demandé'),
	('pouvoir', 'avoir', false, 'passe_compose', 'pu', 'pu', 'pu', 'pu', 'pu', 'pu'),
	('étudier', 'avoir', false, 'imparfait', 'étudiais', 'étudiais', 'étudiait', 'étudiions', 'étudiez', 'étudiaient'),
	('naître', 'être', false, 'future_simple', 'naîtrai', 'naîtras', 'naîtra', 'naîtrons', 'naîtrez', 'naîtront'),
	('mettre', 'avoir', false, 'imperatif', '', 'mets', '', 'mettons', 'mettez', ''),
	('parler', 'avoir', false, 'imparfait', 'parlais', 'parlais', 'parlait', 'parlions', 'parliez', 'parlaient'),
	('finir', 'avoir', false, 'conditionnel', 'finirais', 'finirais', 'finirait', 'finirions', 'finiriez', 'finiraient'),
	('pouvoir', 'avoir', false, 'imperatif', '', 'peux', '', 'pouvons', 'pouvez', ''),
	('faire', 'avoir', false, 'present', 'fais', 'fais', 'fait', 'faisons', 'faites', 'font'),
	('dormir', 'avoir', false, 'subjonctif', 'dorme', 'dormes', 'dorme', 'dormions', 'dormiez', 'dorment'),
	('passer', 'être', false, 'subjonctif', 'passe', 'passes', 'passe', 'passions', 'passiez', 'passent'),
	('aimer', 'avoir', false, 'present', 'aime', 'aimes', 'aime', 'aimons', 'aimez', 'aiment'),
	('enseigner', 'avoir', false, 'future_simple', 'enseignerai', 'enseignerais', 'enseignera', 'enseignerons', 'enseignerez', 'enseigneront'),
	('apprendre', 'avoir', false, 'imparfait', 'apprenais', 'apprenais', 'apprenait', 'apprenions', 'appreniez', 'apprenaient'),
	('offrir', 'avoir', false, 'imparfait', 'offrais', 'offrais', 'offrait', 'offrions', 'offriez', 'offraient'),
	('décrire', 'avoir', false, 'future_simple', 'décrirai', 'décriras', 'décrira', 'décrirons', 'décrirez', 'décriront'),
	('faire', 'avoir', false, 'subjonctif', 'fasse', 'fasses', 'fasse', 'fassions', 'fassiez', 'fassent'),
	('aimer', 'avoir', false, 'imparfait', 'aimais', 'aimais', 'aimait', 'aimions', 'aimiez', 'aimaient'),
	('croire', 'avoir', false, 'subjonctif', 'croie', 'croies', 'croie', 'croyions', 'croyiez', 'croient'),
	('montrer', 'avoir', false, 'conditionnel', 'montrerais', 'montrerais', 'montrerait', 'montrerions', 'montreriez', 'montreraient'),
	('dire', 'avoir', false, 'subjonctif', 'que je dise', 'que tu dises', 'qu''il dise', 'que nous disions', 'que vous disiez', 'qu''ils disent'),
	('décrire', 'avoir', false, 'subjonctif', 'décrive', 'décrives', 'décrive', 'décrivions', 'décriviez', 'décrivent'),
	('devoir', 'avoir', false, 'imperatif', '', 'dois', '', 'devons', 'devez', ''),
	('monter', 'être', false, 'imparfait', 'montais', 'montais', 'montait', 'montions', 'montiez', 'montaient'),
	('boire', 'avoir', false, 'subjonctif', 'boive', 'boives', 'boive', 'buvions', 'buviez', 'boivent'),
	('aimer', 'avoir', false, 'imperatif', '', 'aime', '', 'aimons', 'aimez', ''),
	('confier', 'avoir', false, 'imperatif', '', 'confie', '', 'confiions', 'confiez', ''),
	('lire', 'avoir', false, 'conditionnel', 'lirais', 'lirais', 'lirait', 'lirions', 'liriez', 'liraient'),
	('être', 'avoir', false, 'subjonctif', 'sois', 'sois', 'soit', 'soyons', 'soyez', 'soient'),
	('entrer', 'être', false, 'conditionnel', 'entrerais', 'entrerais', 'entrerait', 'entrerions', 'entreriez', 'entreraient'),
	('écrire', 'avoir', false, 'subjonctif', 'écrive', 'écrives', 'écrive', 'écrivions', 'écriviez', 'écrivent'),
	('ressembler', 'avoir', false, 'conditionnel', 'resserais', 'resserais', 'ressemblerait', 'resserions', 'resseriez', 'ressemblent'),
	('rire', 'avoir', false, 'conditionnel', 'rirais', 'rirais', 'rirait', 'ririons', 'ririez', 'riraient'),
	('rentrer', 'être', false, 'present', 'rentre', 'rentes', 'rentre', 'rentrons', 'rentrez', 'rentrent'),
	('savoir', 'avoir', false, 'future_simple', 'saurai', 'sauras', 'saura', 'saurons', 'saurez', 'sauront'),
	('rester', 'être', false, 'passe_compose', 'suis resté', 'es resté', 'est resté', 'sommes restés', 'êtes restés', 'sont restés'),
	('rester', 'être', false, 'imperatif', '', 'reste', '', 'restons', 'restez', ''),
	('réussir', 'avoir', false, 'passe_compose', 'ai réussi', 'as réussi', 'a réussi', 'avons réussi', 'avez réussi', 'ont réussi'),
	('réussir', 'avoir', false, 'imperatif', '', 'réussis', '', 'réussissons', 'réussissez', ''),
	('se sentir', 'être', true, 'passe_compose', 'me suis senti', 't''es senti', 's''est senti', 'nous sommes sentis', 'vous êtes sentis', 'se sont sentis'),
	('se sentir', 'être', true, 'imperatif', '', 'sente-toi', '', 'sentons-nous', 'sentez-vous', ''),
	('s''habiller', 'être', true, 'subjonctif', 'me habille', 'te habilles', 'se habille', 'nous habillons', 'vous habilliez', 'se habillent'),
	('vivre', 'avoir', false, 'future_simple', 'vivrai', 'vivras', 'vivra', 'vivrons', 'vivrez', 'vivront'),
	('vouloir', 'avoir', false, 'future_simple', 'voudrai', 'voudras', 'voudra', 'voudrons', 'voudrez', 'voudront'),
	('se coucher', 'être', true, 'passe_compose', 'me suis couché', 't''es couché', 's''est couché', 'nous sommes couchés', 'vous êtes couchés', 'se sont couchés'),
	('s''appeler', 'être', true, 'conditionnel', 'm''appellerais', 't''appellerais', 's''appellerait', 'nous appellerions', 'vous appelleriez', 's''appelleraient'),
	('s''asseoir', 'être', true, 'future_simple', 'm''assoirai', 't''assoiras', 's''assoira', 'nous assiérons', 'vous assiérez', 's''asseoiront'),
	('se laver', 'être', true, 'future_simple', 'me laverai', 'te laveras', 'se lavera', 'nous laverons', 'vous laverez', 'se laveront'),
	('travailler', 'avoir', false, 'present', 'travaille', 'travailles', 'travaille', 'travaillons', 'travaillez', 'travaillent'),
	('travailler', 'avoir', false, 'subjonctif', 'travaillasse', 'travaillasses', 'travaillât', 'travaillassions', 'travaillassiez', 'travaillassent'),
	('se souvenir', 'être', true, 'future_simple', 'me souviendrai', 'te souviendras', 'se souviendra', 'nous souviendrons', 'vous souviendrez', 'se souviendront'),
	('sentir', 'avoir', false, 'future_simple', 'sentirai', 'sentiras', 'sentira', 'sentirons', 'sentirez', 'sentiront'),
	('naître', 'être', false, 'imparfait', 'naissais', 'naissais', 'naissait', 'naissions', 'naissiez', 'naissaient'),
	('demander', 'avoir', false, 'imparfait', 'demandais', 'demandais', 'demandait', 'demandions', 'demandiez', 'demandaient'),
	('pouvoir', 'avoir', false, 'imparfait', 'pouvais', 'pouvais', 'pouvait', 'pouvions', 'pouviez', 'pouvaient'),
	('perdre', 'avoir', false, 'imperatif', '', 'perds', '', 'perdons', 'perdez', ''),
	('naître', 'être', false, 'conditionnel', 'naîtrais', 'naîtrais', 'naîtrait', 'naîtrions', 'naîtriez', 'naîtraient'),
	('parler', 'avoir', false, 'future_simple', 'parlerai', 'parleras', 'parlera', 'parlerons', 'parlerez', 'parleront'),
	('demander', 'avoir', false, 'subjonctif', 'demande', 'demandes', 'demande', 'demandions', 'demandiez', 'demandent'),
	('dormir', 'avoir', false, 'conditionnel', 'dormirais', 'dormirais', 'dormirait', 'dormirions', 'dormiriez', 'dormiraient'),
	('passer', 'être', false, 'future_simple', 'passerai', 'passeras', 'passera', 'passerons', 'passerez', 'passeront'),
	('dire', 'avoir', false, 'present', 'dis', 'dis', 'dit', 'disons', 'dites', 'disent'),
	('comprendre', 'avoir', false, 'imparfait', 'comprenais', 'comprenais', 'comprenait', 'comprenions', 'compreniez', 'comprenaient'),
	('décrire', 'avoir', false, 'passe_compose', 'ai décrit', 'as décrit', 'a décrit', 'avons décrit', 'avez décrit', 'ont décrit'),
	('donner', 'avoir', false, 'imperatif', '', 'donne', '', 'donnons', 'donnez', ''),
	('décrire', 'avoir', false, 'imparfait', 'décrivais', 'décrivais', 'décrivait', 'décrivions', 'décriviez', 'décrivaient'),
	('boire', 'avoir', false, 'passe_compose', 'ai bu', 'as bu', 'a bu', 'avons bu', 'avez bu', 'ont bu'),
	('boire', 'avoir', false, 'imparfait', 'buvais', 'buvais', 'buvait', 'buvions', 'buviez', 'buvait'),
	('décrire', 'avoir', false, 'conditionnel', 'décrirais', 'décrirais', 'décrirait', 'décririons', 'décririez', 'décriraient'),
	('boire', 'avoir', false, 'future_simple', 'boirai', 'boiras', 'boira', 'boirons', 'boirez', 'boiront'),
	('descendre', 'être', false, 'future_simple', 'descendrai', 'descendras', 'descendra', 'descendrons', 'descendrez', 'descendront'),
	('dire', 'avoir', false, 'imperatif', '', 'dis', '', 'disons', 'dites', ''),
	('être', 'avoir', false, 'imparfait', 'étais', 'étais', 'était', 'étions', 'étiez', 'étaient'),
	('lire', 'avoir', false, 'imparfait', 'lisais', 'lisais', 'lisait', 'lisions', 'liziez', 'lisaient'),
	('descendre', 'être', false, 'conditionnel', 'descendrais', 'descendrais', 'descendrait', 'descendrions', 'descendriez', 'descendraient'),
	('arriver', 'être', false, 'imperatif', '', 'arrive', '', 'arrivons', 'arrivez', ''),
	('attendre', 'avoir', false, 'imperatif', '', 'attends', '', 'attendons', 'attendez', ''),
	('entrer', 'être', false, 'imparfait', 'entrais', 'entrais', 'entrait', 'entrions', 'entriez', 'entraient'),
	('lire', 'avoir', false, 'subjonctif', 'lise', 'lises', 'lise', 'lisions', 'lisiez', 'lisent'),
	('être', 'avoir', false, 'imperatif', '', 'sois', '', 'soyons', 'soyez', ''),
	('monter', 'être', false, 'imperatif', '', 'monte', '', 'montons', 'montez', ''),
	('répondre', 'avoir', false, 'passe_compose', 'ai répondu', 'as répondu', 'a répondu', 'avons répondu', 'avez répondu', 'ont répondu'),
	('répondre', 'avoir', false, 'imperatif', '', 'réponds', '', 'répondons', 'répondez', ''),
	('rentrer', 'être', false, 'subjonctif', 'rentre', 'rentes', 'rentre', 'rentrions', 'rentriez', 'rentrent'),
	('réfléchir', 'avoir', false, 'conditionnel', 'réfléchirais', 'réfléchirais', 'réfléchirait', 'réfléchirions', 'réfléchiriez', 'réfléchiraient'),
	('retourner', 'être', false, 'conditionnel', 'retournerais', 'retournerais', 'retournerait', 'retournerions', 'retourneriez', 'retourneraient'),
	('regarder', 'avoir', false, 'passe_compose', 'ai regardé', 'as regardé', 'a regardé', 'avons regardé', 'avez regardé', 'ont regardé'),
	('regarder', 'avoir', false, 'future_simple', 'regarderai', 'regarderas', 'regardera', 'regarderons', 'regarderez', 'regarderont'),
	('s''arrêter', 'être', true, 'future_simple', 'm''arrêterai', 't''arrêteras', 's''arrêtera', 'nous nous arrêterons', 'vous vous arrêterez', 's''arrêteront'),
	('s''arrêter', 'être', true, 'subjonctif', 'que je m''arrête', 'que tu t''arrêtes', 'qu''il/elle/on s''arrête', 'que nous nous arrêtons', 'que vous vous arrêtiez', 'qu''ils/elles s''arrêtent'),
	('révéler', 'avoir', false, 'present', 'révèle', 'révèles', 'révèle', 'révélons', 'révélez', 'révèlent'),
	('révéler', 'avoir', false, 'imperatif', '', 'révèle', '', 'révélons', 'révélez', ''),
	('tomber', 'être', false, 'passe_compose', 'suis tombé', 'es tombé', 'est tombé', 'sommes tombés', 'êtes tombés', 'sont tombés'),
	('se promener', 'être', true, 'passe_compose', 'me suis promené(e)', 't''es promené(e)', 's''est promené(e)', 'nous sommes promené(e)s', 'vous êtes promené(e)s', 'se sont promené(e)s'),
	('se promener', 'être', true, 'imperatif', '', 'promène-toi', '', 'promenons-nous', 'promenez-vous', ''),
	('se coucher', 'être', true, 'imperatif', '', 'couche-toi', '', 'couchons-nous', 'couche-toi', ''),
	('s''appeler', 'être', true, 'imparfait', 'm''appelais', 't''appelais', 's''appelait', 'nous appelions', 'vous appeliez', 's''appelaient'),
	('sortir', 'être', false, 'imperatif', '', 'sors', '', 'sortons', 'sortez', ''),
	('revenir', 'être', false, 'passe_compose', 'suis revenu', 'es revenu', 'est revenu', 'sommes revenus', 'êtes revenus', 'sont revenus'),
	('vendre', 'avoir', false, 'passe_compose', 'ai vendu', 'as vendu', 'a vendu', 'avons vendu', 'avez vendu', 'ont vendu'),
	('vendre', 'avoir', false, 'imperatif', '', 'vends', '', 'vendons', 'vendez', ''),
	('trouver', 'avoir', false, 'present', 'trouve', 'trouves', 'trouve', 'trouvons', 'trouvez', 'trouvent'),
	('trouver', 'avoir', false, 'subjonctif', 'trouve', 'trouves', 'trouve', 'trouvions', 'trouviez', 'trouvent'),
	('se souvenir', 'être', true, 'conditionnel', 'me souviendrais', 'te souviendrais', 'se souviendrait', 'nous souviendrions', 'vous souviendriez', 'se souviendraient'),
	('sentir', 'avoir', false, 'conditionnel', 'sentirais', 'sentirais', 'sentirait', 'sentirions', 'sentiriez', 'sentiraient'),
	('mettre', 'avoir', false, 'subjonctif', 'mette', 'mettes', 'mette', 'mettions', 'mettiez', 'mettent'),
	('parler', 'avoir', false, 'passe_compose', 'ai parlé', 'as parlé', 'a parlé', 'avons parlé', 'avez parlé', 'ont parlé'),
	('aller', 'être', false, 'conditionnel', 'irais', 'irais', 'irait', 'irions', 'iriez', 'iraient'),
	('demander', 'avoir', false, 'conditionnel', 'demanderais', 'demanderais', 'demanderait', 'demanderions', 'demanderiez', 'demanderaient'),
	('parler', 'avoir', false, 'conditionnel', 'parlerais', 'parlerais', 'parlerait', 'parlerions', 'parleriez', 'parleraient'),
	('pouvoir', 'avoir', false, 'subjonctif', 'puisse', 'puisses', 'puisse', 'puissions', 'puissiez', 'puissent'),
	('comprendre', 'avoir', false, 'present', 'comprends', 'comprends', 'comprend', 'comprenons', 'comprenez', 'comprennent'),
	('passer', 'être', false, 'conditionnel', 'passerais', 'passerais', 'passerait', 'passerions', 'passeriez', 'passeraient'),
	('promettre', 'avoir', false, 'passe_compose', 'ai promis', 'as promis', 'a promis', 'avons promis', 'avez promis', 'ont promis'),
	('devoir', 'avoir', false, 'present', 'dois', 'dois', 'doit', 'devons', 'devez', 'doivent'),
	('offrir', 'avoir', false, 'present', 'offre', 'offres', 'offre', 'offrons', 'offrez', 'offrent'),
	('manger', 'avoir', false, 'present', 'mange', 'manges', 'mange', 'mangeons', 'mangez', 'mangent'),
	('arriver', 'être', false, 'present', 'arrive', 'arrives', 'arrive', 'arrivons', 'arrivez', 'arrivent'),
	('dire', 'avoir', false, 'imparfait', 'disais', 'disais', 'disait', 'disions', 'disiez', 'disaient'),
	('offrir', 'avoir', false, 'passe_compose', 'ai offert', 'as offert', 'a offert', 'avons offert', 'avez offert', 'ont offert'),
	('devenir', 'être', false, 'imparfait', 'devenais', 'devenais', 'devenait', 'devenions', 'deveniez', 'devenaient'),
	('expliquer', 'avoir', false, 'subjonctif', 'explique', 'explique', 'explique', 'expliquions', 'expliquiez', 'expliquent'),
	('enseigner', 'avoir', false, 'conditionnel', 'enseignerais', 'enseignerais', 'enseignerait', 'enseignerions', 'enseigneriez', 'enseigneraient'),
	('permettre', 'avoir', false, 'future_simple', 'permettrai', 'permettras', 'permettra', 'permettrons', 'permettrez', 'permettront'),
	('apprendre', 'avoir', false, 'conditionnel', 'apprendrais', 'apprendrais', 'apprendrait', 'apprendrions', 'apprendriez', 'apprendraient'),
	('monter', 'être', false, 'present', 'monte', 'montes', 'monte', 'montons', 'montez', 'montent'),
	('croire', 'avoir', false, 'imperatif', '', 'crois', '', 'croyons', 'croyez', ''),
	('promettre', 'avoir', false, 'imperatif', '', 'promets', '', 'promettons', 'promettez', ''),
	('lire', 'avoir', false, 'passe_compose', 'ai lu', 'as lu', 'a lu', 'avons lu', 'avez lu', 'ont lu'),
	('entrer', 'être', false, 'present', 'entre', 'entres', 'entre', 'entrons', 'entrez', 'entrent'),
	('montrer', 'avoir', false, 'imperatif', '', 'montre', '', 'montrons', 'montrez', ''),
	('entendre', 'avoir', false, 'passe_compose', 'ai entendu', 'as entendu', 'a entendu', 'avons entendu', 'avez entendu', 'ont entendu'),
	('écrire', 'avoir', false, 'future_simple', 'écrirai', 'écriras', 'écrira', 'écrirons', 'écrirez', 'écriront'),
	('jouer', 'avoir', false, 'conditionnel', 'jouerais', 'jouerais', 'jouerait', 'jouerions', 'joueriez', 'joueraient'),
	('entrer', 'être', false, 'imperatif', '', 'entre', '', 'entrons', 'entrez', ''),
	('répondre', 'avoir', false, 'conditionnel', 'répondrais', 'répondrais', 'répondrait', 'répondrions', 'répondriez', 'répondraient'),
	('savoir', 'avoir', false, 'imparfait', 'savais', 'savais', 'savait', 'savions', 'saviez', 'savaient'),
	('rester', 'être', false, 'conditionnel', 'resterais', 'resterais', 'resterait', 'resterions', 'resteriez', 'resteraient'),
	('réussir', 'avoir', false, 'conditionnel', 'réussirais', 'réussirais', 'réussirait', 'réussirions', 'réussiriez', 'réussiraient'),
	('se sentir', 'être', true, 'conditionnel', 'me sentirais', 'te sentirais', 'se sentirait', 'nous sentirions', 'vous sentiriez', 'se sentiraient'),
	('regarder', 'avoir', false, 'imparfait', 'regardais', 'regardais', 'regardait', 'regardions', 'regardiez', 'regardaient'),
	('s''arrêter', 'être', true, 'passe_compose', 'me suis arrêté', 't''es arrêté', 's''est arrêté', 'nous nous sommes arrêtés', 'vous vous êtes arrêtés', 'sont arrêtés'),
	('s''arrêter', 'être', true, 'conditionnel', 'm''arrêterais', 't''arrêterais', 's''arrêterait', 'nous nous arrêterions', 'vous vous arrêteriez', 's''arrêteraient'),
	('venir', 'être', false, 'imparfait', 'venais', 'venais', 'venait', 'venions', 'veniez', 'venaient'),
	('se promener', 'être', true, 'conditionnel', 'me promènerais', 'te promènerais', 'se promènerait', 'nous promènerions', 'vous promèneriez', 'se promèneraient'),
	('se coucher', 'être', true, 'present', 'me couche', 'te couches', 'se couche', 'nous couchons', 'vous couchez', 'se couchent'),
	('se coucher', 'être', true, 'conditionnel', 'me coucherais', 'te coucherais', 'se coucherait', 'nous coucherions', 'vous coucheriez', 'se coucheraient'),
	('s''appeler', 'être', true, 'passe_compose', 'me suis appelé', 't''es appelé', 's''est appelé', 'nous sommes appelés', 'vous êtes appelés', 'se sont appelés'),
	('sortir', 'être', false, 'subjonctif', 'sorte', 'sortes', 'sorte', 'sortions', 'sortiez', 'sortent'),
	('revenir', 'être', false, 'imperatif', '', 'reviens', '', 'revenons', 'revenez', ''),
	('se laver', 'être', true, 'imparfait', 'me lavais', 'te lavais', 'se lavait', 'nous lavions', 'vous laviez', 'se lavaient'),
	('travailler', 'avoir', false, 'imparfait', 'travaillais', 'travaillais', 'travaillait', 'travaillions', 'travailliez', 'travaillaient'),
	('se souvenir', 'être', true, 'imparfait', 'me souvenais', 'te souvenais', 'se souvenait', 'nous souvenions', 'vous souveniez', 'se souvenaient'),
	('sentir', 'avoir', false, 'imparfait', 'sentais', 'sentais', 'sentait', 'sentions', 'sentiez', 'sentaient'),
	('chanter', 'avoir', false, 'subjonctif', 'chante', 'chantes', 'chante', 'chantions', 'chantiez', 'chantent'),
	('aller', 'être', false, 'future_simple', 'irai', 'iras', 'ira', 'irons', 'irez', 'iront'),
	('finir', 'avoir', false, 'future_simple', 'finirai', 'finiras', 'finira', 'finirons', 'finirez', 'finiront'),
	('donner', 'avoir', false, 'passe_compose', 'ai donné', 'as donné', 'a donné', 'avons donné', 'avez donné', 'ont donné'),
	('étudier', 'avoir', false, 'imperatif', '', 'étudie', '', 'étudions', 'étudiez', ''),
	('expliquer', 'avoir', false, 'present', 'explique', 'explique', 'explique', 'expliquons', 'expliquez', 'expliquent'),
	('enseigner', 'avoir', false, 'present', 'enseigne', 'enseignes', 'enseigne', 'enseignons', 'enseignez', 'enseignent'),
	('donner', 'avoir', false, 'conditionnel', 'donnerais', 'donnerais', 'donnerait', 'donnerions', 'donneriez', 'donneraient'),
	('montrer', 'avoir', false, 'present', 'montre', 'montres', 'montre', 'montrons', 'montrez', 'montrent'),
	('croire', 'avoir', false, 'future_simple', 'croirai', 'croiras', 'croira', 'croirons', 'croirez', 'croiront'),
	('manger', 'avoir', false, 'passe_compose', 'ai mangé', 'as mangé', 'a mangé', 'avons mangé', 'avez mangé', 'ont mangé'),
	('arriver', 'être', false, 'passe_compose', 'arrivé', 'arrivé', 'arrivé', 'arrivés', 'arrivés', 'arrivés'),
	('aimer', 'avoir', false, 'passe_compose', 'ai aimé', 'as aimé', 'a aimé', 'avons aimé', 'avez aimé', 'ont aimé'),
	('croire', 'avoir', false, 'conditionnel', 'croirais', 'croirais', 'croirait', 'croirions', 'croiriez', 'croiraient'),
	('apprendre', 'avoir', false, 'future_simple', 'apprendrai', 'apprendras', 'apprendra', 'apprendrons', 'apprendrez', 'apprendront'),
	('être', 'avoir', false, 'present', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont'),
	('aimer', 'avoir', false, 'future_simple', 'aimerai', 'aimeras', 'aimera', 'aimerons', 'aimerez', 'aimeront'),
	('confier', 'avoir', false, 'future_simple', 'confierai', 'confieras', 'confiera', 'confierons', 'confierez', 'confieront'),
	('devoir', 'avoir', false, 'subjonctif', 'doive', 'doives', 'doive', 'devions', 'deviez', 'doivent'),
	('monter', 'être', false, 'passe_compose', 'monté', 'monté', 'monté', 'montés', 'montés', 'montés'),
	('découvrir', 'avoir', false, 'passe_compose', 'ai découvert', 'as découvert', 'a découvert', 'avons découvert', 'avez découvert', 'ont découvert'),
	('boire', 'avoir', false, 'conditionnel', 'boirais', 'boirais', 'boirait', 'boirions', 'boiriez', 'boiraient'),
	('apprendre', 'avoir', false, 'imperatif', '', 'apprends', '', 'apprenons', 'apprenez', ''),
	('découvrir', 'avoir', false, 'imparfait', 'découvrais', 'découvrais', 'découvrait', 'découvrions', 'découvriez', 'découvraient'),
	('offrir', 'avoir', false, 'imperatif', '', 'offre', '', 'offrons', 'offrez', ''),
	('découvrir', 'avoir', false, 'future_simple', 'découvrirai', 'découvriras', 'découvrira', 'découvrirons', 'découvrirez', 'découvriront'),
	('monter', 'être', false, 'conditionnel', 'monterais', 'monterais', 'monterait', 'monterions', 'monteriez', 'monteraient'),
	('découvrir', 'avoir', false, 'subjonctif', 'découvre', 'découvres', 'découvre', 'découvrions', 'découvriez', 'découvrent'),
	('lire', 'avoir', false, 'imperatif', '', 'lis', '', 'lisons', 'lisez', ''),
	('jouer', 'avoir', false, 'imperatif', '', 'joue', '', 'jouons', 'jouez', ''),
	('répondre', 'avoir', false, 'present', 'réponds', 'réponds', 'répond', 'répondons', 'répondez', 'répondent'),
	('répondre', 'avoir', false, 'subjonctif', 'réponde', 'répondes', 'réponde', 'répondions', 'répondiez', 'répondent'),
	('savoir', 'avoir', false, 'present', 'sais', 'sais', 'sait', 'savons', 'savez', 'savent'),
	('rentrer', 'être', false, 'imparfait', 'rentraie', 'rentraies', 'rentray', 'rentrant', 'rentriez', 'rentraient'),
	('savoir', 'avoir', false, 'subjonctif', 's sache', 'saches', 'sache', 'sachions', 'sachiez', 'sachent'),
	('réfléchir', 'avoir', false, 'future_simple', 'réfléchirai', 'réfléchiras', 'réfléchira', 'réfléchirons', 'réfléchirez', 'réfléchiront'),
	('retourner', 'être', false, 'future_simple', 'retournerai', 'retourneras', 'retournera', 'retournerons', 'retournerez', 'retourneront'),
	('se lever', 'être', true, 'imparfait', 'me levais', 'te levais', 'se levait', 'nous levions', 'vous leviez', 'se levaient'),
	('s''arrêter', 'être', true, 'present', 'm''arrête', 't''arrêtes', 's''arrête', 'nous arrêtons', 'vous arrêtez', 's''arrêtent'),
	('se lever', 'être', true, 'imperatif', '', 'lève-toi', '', 'levons-nous', 'levez-vous', ''),
	('regarder', 'avoir', false, 'imperatif', '', 'regarde', '', 'regardons', 'regardez', ''),
	('s''habiller', 'être', true, 'present', 'me habille', 'te habilles', 'se habille', 'nous habillons', 'vous habillez', 'se habillent'),
	('révéler', 'avoir', false, 'future_simple', 'révélerai', 'révéleras', 'révélera', 'révélerons', 'révèlerez', 'révéleront'),
	('vivre', 'avoir', false, 'present', 'vis', 'vis', 'vit', 'vivons', 'vivez', 'vivent'),
	('vivre', 'avoir', false, 'subjonctif', 'vive', 'vives', 'vive', 'vivions', 'viviez', 'vivent'),
	('venir', 'être', false, 'subjonctif', 'vienne', 'viennes', 'vienne', 'venions', 'veniez', 'viennent'),
	('vouloir', 'avoir', false, 'present', 'veux', 'veux', 'veut', 'voulons', 'voulez', 'veulent'),
	('vouloir', 'avoir', false, 'subjonctif', 'veuille', 'veuilles', 'veuille', 'veuillons', 'veuillez', 'veuillent'),
	('s''appeler', 'être', true, 'present', 'm''appelle', 't''appelles', 's''appelle', 'nous appelons', 'vous appelez', 's''appellent'),
	('sortir', 'être', false, 'conditionnel', 'sortirais', 'sortirais', 'sortirait', 'sortirions', 'sortiriez', 'sortiraient'),
	('revenir', 'être', false, 'imparfait', 'revenais', 'revenais', 'revenait', 'revenions', 'reveniez', 'revenaient'),
	('revenir', 'être', false, 'subjonctif', 'revienne', 'reviennes', 'revienne', 'revenions', 'reveniez', 'reviennent'),
	('vendre', 'avoir', false, 'imparfait', 'vendais', 'vendais', 'vendait', 'vendions', 'vendiez', 'vendaient'),
	('trouver', 'avoir', false, 'future_simple', 'trouverai', 'trouveras', 'trouvera', 'trouverons', 'trouverez', 'trouveront'),
	('travailler', 'avoir', false, 'imperatif', '', 'travaille', '', 'travaillons', 'travaillez', ''),
	('se souvenir', 'être', true, 'present', 'me souviens', 'te souviens', 'se souvient', 'nous souvenons', 'vous souvenez', 'se souviennent'),
	('se souvenir', 'être', true, 'subjonctif', 'que je me souvienne', 'que tu te souviennes', 'qu''il se souvienne', 'que nous nous souvenions', 'que vous vous souveniez', 'qu''ils se souviennent'),
	('sentir', 'avoir', false, 'present', 'sens', 'sens', 'sent', 'sentons', 'sentez', 'sentent'),
	('aller', 'être', false, 'imparfait', 'allais', 'allais', 'allait', 'allions', 'alliez', 'allaient'),
	('dormir', 'avoir', false, 'present', 'dors', 'dors', 'dort', 'dormons', 'dormez', 'dorment'),
	('chanter', 'avoir', false, 'imperatif', '', 'chante', '', 'chantons', 'chantez', ''),
	('pouvoir', 'avoir', false, 'future_simple', 'pourrai', 'pourras', 'pourra', 'pourrons', 'pourrez', 'pourront'),
	('naître', 'être', false, 'subjonctif', 'naisse', 'n aisses', 'naisse', 'naissions', 'naissiez', 'naissent'),
	('pouvoir', 'avoir', false, 'conditionnel', 'pourrais', 'pourrais', 'pourrait', 'pourrions', 'pourriez', 'pourraient'),
	('dormir', 'avoir', false, 'future_simple', 'dormirai', 'dormiras', 'dormira', 'dormirons', 'dormirez', 'dormiront'),
	('aller', 'être', false, 'imperatif', '', 'va', '', 'allons', 'allez', ''),
	('partir', 'être', false, 'conditionnel', 'partirais', 'partirais', 'partirait', 'partirions', 'partiriez', 'partiraient'),
	('donner', 'avoir', false, 'future_simple', 'donnerai', 'donneras', 'donnera', 'donnerons', 'donnez', 'donneront'),
	('promettre', 'avoir', false, 'present', 'promets', 'promets', 'promet', 'promettons', 'promettez', 'promettent'),
	('faire', 'avoir', false, 'passe_compose', 'ai fait', 'as fait', 'a fait', 'avons fait', 'avez fait', 'ont fait'),
	('devenir', 'être', false, 'present', 'deviens', 'deviens', 'devient', 'devenons', 'devenez', 'deviennent'),
	('partir', 'être', false, 'imperatif', '', 'pars', '', 'partons', 'partez', ''),
	('apprendre', 'avoir', false, 'passe_compose', 'ai appris', 'as appris', 'a appris', 'avons appris', 'avez appris', 'ont appris'),
	('passer', 'être', false, 'imperatif', '', 'passe', '', 'passons', 'passez', ''),
	('promettre', 'avoir', false, 'future_simple', 'promettrai', 'promettras', 'promettra', 'promettrons', 'promettrez', 'promettront'),
	('confier', 'avoir', false, 'passe_compose', 'ai confié', 'as confié', 'a confié', 'avons confié', 'avez confié', 'ont confié'),
	('confier', 'avoir', false, 'imparfait', 'confiais', 'confiais', 'confiait', 'confions', 'confiez', 'confiaient'),
	('prendre', 'avoir', false, 'conditionnel', 'prendrais', 'prendrays', 'prendrait', 'prendrions', 'prendriez', 'prendraient'),
	('lire', 'avoir', false, 'present', 'lis', 'lis', 'lit', 'lisons', 'lisez', 'lisent'),
	('descendre', 'être', false, 'imparfait', 'descendais', 'descendais', 'descendait', 'descendions', 'descendiez', 'descendaient'),
	('enseigner', 'avoir', false, 'imperatif', '', 'enseigne', '', 'enseignons', 'enseignez', ''),
	('écrire', 'avoir', false, 'present', 'écris', 'écris', 'écrit', 'écrivons', 'écrivez', 'écrivent'),
	('offrir', 'avoir', false, 'subjonctif', 'offre', 'offres', 'offre', 'offrions', 'offriez', 'offrent'),
	('écrire', 'avoir', false, 'passe_compose', 'ai écrit', 'as écrit', 'a écrit', 'avons écrit', 'avez écrit', 'ont écrit'),
	('lire', 'avoir', false, 'future_simple', 'lirai', 'liras', 'lira', 'lirons', 'lirez', 'liront'),
	('être', 'avoir', false, 'conditionnel', 'serais', 'serais', 'serait', 'serions', 'seriez', 'seraient'),
	('jouer', 'avoir', false, 'imparfait', 'jouais', 'jouais', 'jouait', 'jouions', 'jouiez', 'jouaient'),
	('entendre', 'avoir', false, 'future_simple', 'entendrai', 'entendras', 'entendra', 'entendrons', 'entendrez', 'entendront'),
	('jouer', 'avoir', false, 'future_simple', 'jouerai', 'joueras', 'jouera', 'jouerons', 'jouerez', 'joueront'),
	('jouer', 'avoir', false, 'subjonctif', 'joue', 'joues', 'joue', 'jouions', 'jouiez', 'jouent'),
	('ressembler', 'avoir', false, 'imparfait', 'ressemble', 'ressemblais', 'ressemblait', 'ressemblions', 'ressembliez', 'ressemblaient'),
	('rire', 'avoir', false, 'imparfait', 'riais', 'riais', 'riait', 'riions', 'riiez', 'riaient'),
	('rentrer', 'être', false, 'conditionnel', 'rentrerais', 'rentrerais', 'rentrerait', 'rentrerions', 'rentreriez', 'rentreraient'),
	('réfléchir', 'avoir', false, 'imparfait', 'réfléchissais', 'réfléchissais', 'réfléchissait', 'réfléchissions', 'réfléchissiez', 'réfléchissaient'),
	('retourner', 'être', false, 'imparfait', 'retournais', 'retournais', 'retournait', 'retournions', 'retourniez', 'retournaient'),
	('se lever', 'être', true, 'conditionnel', 'me lèverais', 'te lèverais', 'se lèverait', 'nous nous lèverions', 'vous vous lèveriez', 'se lèveraient'),
	('regarder', 'avoir', false, 'conditionnel', 'regarderais', 'regarderais', 'regarderait', 'regarderions', 'regarderiez', 'regarderaient'),
	('révéler', 'avoir', false, 'imparfait', 'révélai', 'révélas', 'révélait', 'révélions', 'révéliez', 'révélaient'),
	('révéler', 'avoir', false, 'subjonctif', 'révèle', 'révèles', 'révèle', 'révélions', 'révéliez', 'révèlent'),
	('tomber', 'être', false, 'present', 'tombe', ' tombes', 'tombe', 'tombons', 'tombez', 'tombent'),
	('venir', 'être', false, 'present', 'viens', 'viens', 'vient', 'venons', 'venez', 'viennent'),
	('venir', 'être', false, 'future_simple', 'viendrai', 'viendras', 'viendra', 'viendrons', 'viendrez', 'viendront'),
	('se promener', 'être', true, 'present', 'me promène', 'te promènes', 'se promène', 'nous promenons', 'vous promenez', 'se promènent'),
	('se promener', 'être', true, 'subjonctif', 'que je me promène', 'que tu te promènes', 'qu''il/elle se promène', 'que nous nous promenions', 'que vous vous promeniez', 'qu''ils/elles se promenent'),
	('se coucher', 'être', true, 'subjonctif', 'que je me couche', 'que tu te couches', 'qu''il/elle/on se couche', 'que nous nous couchions', 'que vous vous couchiez', 'qu''ils/elles se couchent'),
	('sortir', 'être', false, 'future_simple', 'sortirai', 'sortiras', 'sortira', 'sortirons', 'sortez', 'sortiront'),
	('revenir', 'être', false, 'present', 'reviens', 'reviens', 'revient', 'revenons', 'revenez', 'reviennent'),
	('revenir', 'être', false, 'conditionnel', 'reviendrais', 'reviendrais', 'reviendrait', 'reviendrions', 'reviendriez', 'reviendraient'),
	('voir', 'avoir', false, 'future_simple', 'verrai', 'verras', 'verra', 'verrons', 'verrez', 'verront'),
	('vendre', 'avoir', false, 'present', 'vends', 'vends', 'vend', 'vendons', 'vendez', 'vendent'),
	('vendre', 'avoir', false, 'subjonctif', 'vende', 'vendes', 'vende', 'vendions', 'vendiez', 'vendent'),
	('trouver', 'avoir', false, 'imparfait', 'trouvais', 'trouvais', 'trouvait', 'trouvions', 'trouviez', 'trouvaient'),
	('servir', 'avoir', false, 'present', 'sers', 'sers', 'sert', 'servons', 'servez', 'servent'),
	('servir', 'avoir', false, 'subjonctif', 'serve', 'serves', 'serve', 'servions', 'serviez', 'servent'),
	('suivre', 'avoir', false, 'present', 'suis', 'suis', 'suit', 'suivons', 'suivez', 'suivent'),
	('suivre', 'avoir', false, 'subjonctif', 'suive', 'suives', 'suive', 'suivions', 'suiviez', 'suivent'),
	('perdre', 'avoir', false, 'subjonctif', 'perde', 'perdes', 'perde', 'perdions', 'perdiez', 'perdent'),
	('partir', 'être', false, 'passe_compose', 'suis parti', 'es parti', 'est parti', 'sommes partis', 'êtes partis', 'sont partis'),
	('donner', 'avoir', false, 'present', 'donne', 'donnes', 'donne', 'donnons', 'donnez', 'donnent'),
	('étudier', 'avoir', false, 'subjonctif', 'étudie', 'étudies', 'étudie', 'étudions', 'étudiez', 'étudient'),
	('passer', 'être', false, 'passe_compose', 'étè passé', 'es passé', 'est passé', 'sommes passés', 'êtes passés', 'sont passés'),
	('partir', 'être', false, 'future_simple', 'partirai', 'partiras', 'partira', 'partirons', 'partirez', 'partiront'),
	('partir', 'être', false, 'subjonctif', 'parte', 'partes', 'parte', 'partions', 'partiez', 'partent'),
	('expliquer', 'avoir', false, 'imparfait', 'expliquais', 'expliquais', 'expliquait', 'expliquions', 'expliquiez', 'expliquaient'),
	('donner', 'avoir', false, 'subjonctif', 'donne', 'donnes', 'donne', 'donnions', 'donniez', 'donne'),
	('devenir', 'être', false, 'passe_compose', 'devenu(e)', 'devenu(e)', 'devenu(e)', 'devenus(es)', 'devenus(es)', 'devenus(es)'),
	('prendre', 'avoir', false, 'passe_compose', 'ai pris', 'as pris', 'a pris', 'avons pris', 'avez pris', 'ont pris'),
	('attendre', 'avoir', false, 'passe_compose', 'ai attendu', 'as attendu', 'a attendu', 'avons attendu', 'avez attendu', 'ont attendu'),
	('comprendre', 'avoir', false, 'conditionnel', 'comprendrais', 'comprendrais', 'comprendrait', 'comprendreions', 'comprendrez', 'comprendraient'),
	('prendre', 'avoir', false, 'future_simple', 'prendrai', 'prendras', 'prendra', 'prendrons', 'prendrez', 'prendront'),
	('arriver', 'être', false, 'imparfait', 'arrivais', 'arrivais', 'arrivait', 'arrivions', 'arriviez', 'arrivaient'),
	('dire', 'avoir', false, 'conditionnel', 'dirais', 'dirais', 'dirait', 'dirions', 'diriez', 'diraient'),
	('offrir', 'avoir', false, 'future_simple', 'offrirai', 'offriras', 'offrira', 'offrirons', 'offrirez', 'offriront'),
	('devenir', 'être', false, 'conditionnel', 'deviendrais', 'deviendrais', 'deviendrait', 'deviendrions', 'deviendriez', 'deviendraient'),
	('permettre', 'avoir', false, 'conditionnel', 'permettrais', 'permettrais', 'permettrait', 'permettrions', 'permettriez', 'permettraient'),
	('devenir', 'être', false, 'subjonctif', 'devienne', 'deviennes', 'devienne', 'devenions', 'deveniez', 'deviennent'),
	('prendre', 'avoir', false, 'subjonctif', 'prenne', 'prennes', 'prenne', 'prenions', 'preniez', 'prennent'),
	('arriver', 'être', false, 'conditionnel', 'arriverais', 'arriverais', 'arriverait', 'arriverions', 'arriveriez', 'arriveraient'),
	('confier', 'avoir', false, 'conditionnel', 'confierais', 'confierais', 'confierait', 'confierions', 'confieriez', 'confieraient'),
	('confier', 'avoir', false, 'subjonctif', 'que je confie', 'que tu confies', 'qu''il/elle/on confie', 'que nous confiions', 'que vous confiiez', 'qu''ils/elles confient'),
	('écrire', 'avoir', false, 'imparfait', 'écrivais', 'écrivais', 'écrivait', 'écrivions', 'écriviez', 'écrivaient'),
	('boire', 'avoir', false, 'imperatif', '', 'bois', '', 'buvons', 'buvez', ''),
	('entendre', 'avoir', false, 'conditionnel', 'entendrais', 'entendrais', 'entendrait', 'entendrions', 'entendriez', 'entendraient'),
	('découvrir', 'avoir', false, 'imperatif', '', 'découvre', '', 'découvrons', 'découvrez', ''),
	('entendre', 'avoir', false, 'imperatif', '', 'entends', '', 'entendons', 'entendez', ''),
	('répondre', 'avoir', false, 'imparfait', 'répondais', 'répondais', 'répondait', 'répondions', 'répondiez', 'répondaient'),
	('savoir', 'avoir', false, 'passe_compose', 'ai su', 'as su', 'a su', 'avons su', 'avez su', 'ont su'),
	('savoir', 'avoir', false, 'imperatif', '', 'sache', '', 'sachons', 'sachez', ''),
	('réfléchir', 'avoir', false, 'present', 'réfléchis', 'réfléchis', 'réfléchit', 'réfléchissons', 'réfléchissez', 'réfléchissent'),
	('réfléchir', 'avoir', false, 'subjonctif', 'réfléchisse', 'réfléchisses', 'réfléchisse', 'réfléchissions', 'réfléchissiez', 'réfléchissent'),
	('retourner', 'être', false, 'present', 'retourne', 'retournes', 'retourne', 'retournons', 'retournez', 'retournent'),
	('retourner', 'être', false, 'subjonctif', 'retourne', 'retournes', 'retourne', 'retournions', 'retourniez', 'retournent'),
	('se lever', 'être', true, 'present', 'me lève', 'te lèves', 'se lève', 'nous levons', 'vous levez', 'se lèvent'),
	('se lever', 'être', true, 'future_simple', 'me lèverai', 'te lèveras', 'se lèvera', 'nous nous lèverons', 'vous vous lèverez', 'se lèveront'),
	('se lever', 'être', true, 'subjonctif', 'que je me lève', 'que tu te lèves', 'qu''il/elle se lève', 'que nous nous levions', 'que vous vous leviez', 'qu''ils/elles se lèvent'),
	('regarder', 'avoir', false, 'subjonctif', 'que je regarde', 'que tu regardes', 'qu''il regarde', 'que nous regardions', 'que vous regardiez', 'qu''ils regardent'),
	('tenir', 'avoir', false, 'imparfait', 'tenais', 'tenais', 'tenait', 'tenions', 'teniez', 'tenaient'),
	('s''arrêter', 'être', true, 'imperatif', '', 'arrête-toi', '', 'arrêtons-nous', 'arrêtez-vous', ''),
	('s''habiller', 'être', true, 'passe_compose', 'me suis habillé', 't''es habillé', 's''est habillé', 'nous sommes habillés', 'vous êtes habillés', 'se sont habillés'),
	('s''habiller', 'être', true, 'conditionnel', 'me habillerais', 'te habillerais', 'se habillerait', 'nous habillerions', 'vous habilleriez', 'se habilleraient'),
	('révéler', 'avoir', false, 'conditionnel', 'révèlerais', 'révèlerais', 'révèlerait', 'révèlerions', 'révèleriez', 'révèleraient'),
	('vivre', 'avoir', false, 'passe_compose', 'ai vécu', 'as vécu', 'a vécu', 'avons vécu', 'avez vécu', 'ont vécu'),
	('vivre', 'avoir', false, 'imperatif', '', 'vis', '', 'vivons', 'vivez', ''),
	('tomber', 'être', false, 'imperatif', '', 'tombe', '', 'tombons', 'tombez', ''),
	('venir', 'être', false, 'imperatif', '', 'viens', '', 'venons', 'venez', ''),
	('vouloir', 'avoir', false, 'passe_compose', 'ai voulu', 'as voulu', 'a voulu', 'avons voulu', 'avez voulu', 'ont voulu'),
	('s''appeler', 'être', true, 'future_simple', 'm''appellerai', 't''appelleras', 's''appellera', 'nous appellerons', 'vous appellerez', 's''appelleront'),
	('s''asseoir', 'être', true, 'passe_compose', 'me suis assis', 't''es assis', 's''est assis', 'nous sommes assis', 'vous êtes assis', 'sont assis'),
	('s''asseoir', 'être', true, 'imperatif', '', 'assieds-toi', '', 'asseyons-nous', 'asseyez-vous', ''),
	('voir', 'avoir', false, 'imparfait', 'voyais', 'voyais', 'voyait', 'voyions', 'voyiez', 'voyait'),
	('voir', 'avoir', false, 'imperatif', '', 'vois', '', 'voyons', 'voyez', ''),
	('sentir', 'avoir', false, 'subjonctif', 'sente', 'sentes', 'sente', 'sentions', 'sentiez', 'sentent'),
	('avoir', 'avoir', false, 'subjonctif', 'aie', 'aies', 'ait', 'ayons', 'ayez', 'aient'),
	('dormir', 'avoir', false, 'imparfait', 'dormais', 'dormais', 'dormait', 'dormions', 'dormiez', 'dormaient'),
	('aller', 'être', false, 'subjonctif', 'aille', 'ailles', 'aille', 'allions', 'alliez', 'aillent'),
	('donner', 'avoir', false, 'imparfait', 'donner', 'donnais', 'donner', 'donnions', 'donniez', 'donnaient'),
	('décrire', 'avoir', false, 'present', 'décris', 'décris', 'décrit', 'décrivons', 'décrivez', 'découvrent'),
	('dormir', 'avoir', false, 'imperatif', '', 'dors', '', 'dormons', 'dormez', ''),
	('expliquer', 'avoir', false, 'future_simple', 'expliquerai', 'expliqueras', 'expliquera', 'expliquerons', 'expliquerez', 'expliqueront'),
	('promettre', 'avoir', false, 'imparfait', 'promettais', 'promettais', 'promettait', 'promettions', 'promettiez', 'promettaient'),
	('faire', 'avoir', false, 'future_simple', 'ferai', 'feras', 'fera', 'ferons', 'ferez', 'feront'),
	('confier', 'avoir', false, 'present', 'confie', 'confies', 'confie', 'confions', 'confiez', 'confient'),
	('devoir', 'avoir', false, 'imparfait', 'devais', 'devais', 'devait', 'devions', 'deviez', 'devaient'),
	('descendre', 'être', false, 'present', 'descends', 'descends', 'descend', 'descendons', 'descendez', 'descendent'),
	('montrer', 'avoir', false, 'future_simple', 'montrerai', 'montreras', 'montrera', 'montrerons', 'montrerez', 'montreront'),
	('attendre', 'avoir', false, 'imparfait', 'attendais', 'attendais', 'attendait', 'attendions', 'attendiez', 'attendaient'),
	('comprendre', 'avoir', false, 'subjonctif', 'comprenne', 'comprennes', 'comprenne', 'comprenions', 'compreniez', 'comprennent'),
	('manger', 'avoir', false, 'future_simple', 'mangerai', 'mangeras', 'mangera', 'mangerons', 'mangerez', 'mangeront'),
	('arriver', 'être', false, 'future_simple', 'arriverai', 'arriveras', 'arrivera', 'arriverons', 'arriverez', 'arriveront'),
	('attendre', 'avoir', false, 'future_simple', 'attendrai', 'attendras', 'attendra', 'attendrons', 'attendrez', 'attendront'),
	('manger', 'avoir', false, 'conditionnel', 'mangerais', 'mangerais', 'mangerait', 'mangerions', 'mangeriez', 'mangeraient'),
	('attendre', 'avoir', false, 'conditionnel', 'attendrais', 'attendrais', 'attendrait', 'attendrions', 'attendriez', 'attendraient'),
	('manger', 'avoir', false, 'subjonctif', 'que je mange', 'que tu manges', 'qu''il mange', 'que nous mangions', 'que vous mangiez', 'qu''ils mangent'),
	('aimer', 'avoir', false, 'subjonctif', 'aime', 'aimes', 'aime', 'aimions', 'aimiez', 'aiment'),
	('entrer', 'être', false, 'passe_compose', 'suis entré', 'es entré', 'est entré', 'sommes entrés', 'êtes entrés', 'sont entrés'),
	('jouer', 'avoir', false, 'passe_compose', 'ai joué', 'as joué', 'a joué', 'avons joué', 'avez joué', 'ont joué'),
	('monter', 'être', false, 'future_simple', 'monterai', 'monteras', 'montera', 'monterons', 'monterez', 'monteront'),
	('écrire', 'avoir', false, 'conditionnel', 'écrirais', 'écrirais', 'écrirait', 'écririons', 'écririez', 'écriraient'),
	('ressembler', 'avoir', false, 'present', 'ressembles', 'ressemble', 'ressembler', 'ressembons', 'ressembtez', 'ressembent'),
	('ressembler', 'avoir', false, 'subjonctif', 'que je ressemble', 'que tu ressembles', 'qu''il/elle/on ressemble', 'que nous ressemblions', 'que vous ressembliez', 'qu''ils/elles ressemblent'),
	('rire', 'avoir', false, 'present', 'ris', 'ris', 'rit', 'rions', 'riez', 'rient'),
	('rire', 'avoir', false, 'subjonctif', 'rie', 'ries', 'rie', 'riions', 'riiez', 'rient'),
	('rentrer', 'être', false, 'future_simple', 'rentrerai', 'renteras', 'rentrera', 'rentrerons', 'rentrerez', 'rentreront'),
	('rester', 'être', false, 'imparfait', 'restais', 'restais', 'restait', 'restions', 'restiez', 'restaient'),
	('réussir', 'avoir', false, 'imparfait', 'réussissais', 'réussissais', 'réussissait', 'réussissions', 'réussissiez', 'réussissaient'),
	('se sentir', 'être', true, 'imparfait', 'me sentais', 'te sentais', 'se sentait', 'nous sentions', 'vous sentiez', 'se sentaient'),
	('tenir', 'avoir', false, 'passe_compose', 'ai tenu', 'as tenu', 'a tenu', 'avons tenu', 'avez tenu', 'ont tenu'),
	('tenir', 'avoir', false, 'future_simple', 'tiendrai', 'tiendras', 'tiendra', 'tiendrons', 'tiendrez', 'tiendront'),
	('tenir', 'avoir', false, 'imperatif', '', 'tiens', '', 'tenons', 'tenez', ''),
	('s''habiller', 'être', true, 'future_simple', 'me habillerai', 'te habilleras', 'se habillera', 'nous habillerons', 'vous habillerez', 'se habilleront'),
	('vivre', 'avoir', false, 'conditionnel', 'vivrais', 'vivrais', 'vivrait', 'vivrions', 'vivriez', 'vivraient'),
	('tomber', 'être', false, 'subjonctif', 'tombe', 'tombes', 'tombe', 'tombions', 'tombiez', 'tombent'),
	('venir', 'être', false, 'conditionnel', 'viendrais', 'viendrais', 'viendrait', 'viendrions', 'viendriez', 'viendraient'),
	('vouloir', 'avoir', false, 'conditionnel', 'voudrais', 'voudrais', 'voudrait', 'voudrions', 'voudriez', 'voudraient'),
	('sortir', 'être', false, 'passe_compose', 'suis sorti', 'es sorti', 'est sorti', 'sommes sortis', 'êtes sortis', 'sont sortis'),
	('s''asseoir', 'être', true, 'conditionnel', 'm''assoirais', 't''assoirais', 's''assoiraient', 'nous assiérions', 'vous assiériez', 's''asseyiraient'),
	('voir', 'avoir', false, 'passe_compose', 'ai vu', 'as vu', 'a vu', 'avons vu', 'avez vu', 'ont vu'),
	('voir', 'avoir', false, 'conditionnel', 'verrais', 'verrais', 'verrait', 'verrions', 'verriez', 'verraient'),
	('se laver', 'être', true, 'conditionnel', 'me laverais', 'te laverais', 'se laverait', 'nous laverions', 'vous laveriez', 'se laveraient'),
	('travailler', 'avoir', false, 'future_simple', 'travaillerai', 'travailleras', 'travaillera', 'travaillerons', 'travaillerez', 'travailleront'),
	('servir', 'avoir', false, 'passe_compose', 'ai servi', 'as servi', 'a servi', 'avons servi', 'avez servi', 'ont servi'),
	('servir', 'avoir', false, 'imperatif', '', 'sers', '', 'servons', 'servez', ''),
	('suivre', 'avoir', false, 'passe_compose', 'ai suivi', 'as suivi', 'a suivi', 'avons suivi', 'avez suivi', 'ont suivi'),
	('suivre', 'avoir', false, 'imperatif', '', 'suis', '', 'suivons', 'suivez', ''),
	('finir', 'avoir', false, 'imparfait', 'finissais', 'finissais', 'finissait', 'finissions', 'finissiez', 'finissaient'),
	('étudier', 'avoir', false, 'future_simple', 'étudierai', 'étudieras', 'étudiera', 'étudierons', 'étudierez', 'étudieront'),
	('ouvrir', 'avoir', false, 'imperatif', '', 'ouvre', '', 'ouvrons', 'ouvrez', ''),
	('demander', 'avoir', false, 'future_simple', 'demanderai', 'demanderas', 'demandera', 'demanderons', 'demanderez', 'demanderont'),
	('naître', 'être', false, 'imperatif', '', 'nais', '', 'naissons', 'naissez', ''),
	('finir', 'avoir', false, 'imperatif', '', 'finis', '', 'finissons', 'finissez', ''),
	('parler', 'avoir', false, 'imperatif', '', 'parle', '', 'parlons', 'parlez', ''),
	('enseigner', 'avoir', false, 'passe_compose', 'ai enseigné', 'as enseigné', 'a enseigné', 'avons enseigné', 'avez enseigné', 'ont enseigné'),
	('apprendre', 'avoir', false, 'present', 'apprends', 'apprends', 'apprend', 'apprenons', 'apprenez', 'apprennent'),
	('dire', 'avoir', false, 'passe_compose', 'ai dit', 'as dit', 'a dit', 'avons dit', 'avez dit', 'ont dit'),
	('enseigner', 'avoir', false, 'imparfait', 'enseignais', 'enseignais', 'enseignait', 'enseignions', 'enseigniez', 'enseignaient'),
	('montrer', 'avoir', false, 'passe_compose', 'ai montré', 'as montré', 'a montré', 'avons montré', 'avez montré', 'ont montré'),
	('devoir', 'avoir', false, 'passe_compose', 'ai dû', 'as dû', 'a dû', 'avons dû', 'avez dû', 'ont dû'),
	('expliquer', 'avoir', false, 'conditionnel', 'expliquerais', 'expliquerais', 'expliquerait', 'expliquerions', 'expliqueriez', 'expliqueraient'),
	('comprendre', 'avoir', false, 'future_simple', 'comprendrai', 'comprendras', 'comprendra', 'comprendreons', 'comprendrez', 'comprendront'),
	('permettre', 'avoir', false, 'imparfait', 'permettais', 'permettais', 'permettait', 'permettions', 'permettiez', 'permettaient'),
	('faire', 'avoir', false, 'conditionnel', 'ferais', 'ferais', 'ferait', 'ferions', 'feriez', 'feraient'),
	('dire', 'avoir', false, 'future_simple', 'dirai', 'diras', 'dira', 'dirons', 'direz', 'diront'),
	('devenir', 'être', false, 'future_simple', 'deviendrai', 'deviendras', 'deviendra', 'deviendrons', 'deviendrez', 'deviendront'),
	('devoir', 'avoir', false, 'conditionnel', 'devrais', 'devrais', 'devrait', 'devrions', 'devriez', 'devraient'),
	('faire', 'avoir', false, 'imperatif', '', 'fais', '', 'faisons', 'faites', ''),
	('découvrir', 'avoir', false, 'present', 'découvre', 'découvres', 'découvre', 'découvrons', 'découvrez', 'découvrent'),
	('offrir', 'avoir', false, 'conditionnel', 'offrirais', 'offrirais', 'offrirait', 'offririons', 'offririez', 'offriraient'),
	('permettre', 'avoir', false, 'subjonctif', 'permette', 'permettes', 'permette', 'permettions', 'permettiez', 'permettent'),
	('aimer', 'avoir', false, 'conditionnel', 'aimerais', 'aimerais', 'aimerait', 'aimerions', 'aimeriez', 'aimeraient'),
	('prendre', 'avoir', false, 'imperatif', '', 'prends', '', 'prenons', 'prenez', ''),
	('attendre', 'avoir', false, 'subjonctif', 'attende', 'attendes', 'attende', 'attendions', 'attendiez', 'attendent'),
	('découvrir', 'avoir', false, 'conditionnel', 'découvrirais', 'découvrirais', 'découvrirait', 'découvririons', 'découvririez', 'découvriraient'),
	('entrer', 'être', false, 'future_simple', 'entrerai', 'entreras', 'entrera', 'entrerons', 'entrerez', 'entreront'),
	('écrire', 'avoir', false, 'imperatif', '', 'écris', '', 'écrivons', 'écrivez', ''),
	('répondre', 'avoir', false, 'future_simple', 'répondrai', 'répondras', 'répondra', 'répondrons', 'répondrez', 'répondront'),
	('rentrer', 'être', false, 'passe_compose', 'suis rentré(e)', 'es rentré(e)', 'est rentré(e)', 'sommes rentrés(e)s', 'êtes rentrés(e)s', 'sont rentrés(e)s'),
	('rentrer', 'être', false, 'imperatif', 'rentre', 'rentre', '', 'rentrons', 'rentre', ''),
	('rester', 'être', false, 'future_simple', 'resterai', 'resteras', 'restera', 'resterons', 'resterez', 'resteront'),
	('réussir', 'avoir', false, 'future_simple', 'réussirai', 'réussiras', 'réussira', 'réussirons', 'réussirez', 'réussiront'),
	('se sentir', 'être', true, 'future_simple', 'me sentirai', 'te sentiras', 'se sentira', 'nous sentirons', 'vous sentirez', 'se sentiront'),
	('tenir', 'avoir', false, 'present', 'tiens', 'tiens', 'tient', 'tenons', 'tenez', 'tiennent'),
	('s''habiller', 'être', true, 'imperatif', '', 'habille-toi', '', 'habillons-nous', 'habillez-vous', ''),
	('tomber', 'être', false, 'imparfait', 'tombais', 'tombais', 'tombait', 'tombions', 'tombiez', 'tombaient'),
	('venir', 'être', false, 'passe_compose', 'venu', 'venu', 'venu', 'venue', 'venue', 'venus'),
	('se promener', 'être', true, 'imparfait', 'me promenais', 'te promenais', 'se promenait', 'nous promenions', 'vous promeniez', 'se promenaient'),
	('se coucher', 'être', true, 'imparfait', 'me couchais', 'te couchais', 'se couchait', 'nous couchions', 'vous couchiez', 'se couchaient'),
	('s''appeler', 'être', true, 'subjonctif', 'que je m''appelle', 'que tu t''appelles', 'qu''il/elle s''appelle', 'que nous nous appelions', 'que vous vous appeliez', 'qu''ils/elles s''appellent'),
	('s''asseoir', 'être', true, 'present', 'm''assieds', 't''assieds', 's''assied', 'nous asseyons', 'vous asseyez', 's''asseyent'),
	('s''asseoir', 'être', true, 'subjonctif', 'que je m''asseye', 'que tu t''asseyes', 'qu''il/elle s''asseye', 'que nous nous asseyions', 'que vous vous asseyiez', 'qu''ils/elles s''asseyent'),
	('voir', 'avoir', false, 'subjonctif', 'voie', 'voies', 'voie', 'voyions', 'voyiez', 'voient'),
	('se laver', 'être', true, 'present', 'me lave', 'te laves', 'se lave', 'nous lavons', 'vous lavez', 'se lavent'),
	('se laver', 'être', true, 'subjonctif', 'que je me lave', 'que tu te laves', 'qu''il/elle se lave', 'que nous nous lavions', 'que vous vous laviez', 'qu''ils/elles se lavent'),
	('travailler', 'avoir', false, 'passe_compose', 'ai travaillé', 'as travaillé', 'a travaillé', 'avons travaillé', 'avez travaillé', 'ont travaillé'),
	('servir', 'avoir', false, 'imparfait', 'servais', 'servais', 'servait', 'servions', 'serviez', 'servaient'),
	('suivre', 'avoir', false, 'imparfait', 'suivais', 'suivais', 'suivait', 'suivions', 'suiviez', 'suivaient'),
	('partir', 'être', false, 'present', 'pars', 'pars', 'part', 'partons', 'partez', 'partent'),
	('avoir', 'avoir', false, 'imperatif', '', 'a', '', 'ayons', 'ayez', ''),
	('dormir', 'avoir', false, 'passe_compose', 'ai dormi', 'as dormi', 'a dormi', 'avons dormi', 'avez dormi', 'ont dormi'),
	('finir', 'avoir', false, 'subjonctif', 'finisse', 'finisses', 'finisse', 'finissions', 'finissiez', 'finissent'),
	('passer', 'être', false, 'imparfait', 'passais', 'passais', 'passait', 'passions', 'passiez', 'passaient'),
	('demander', 'avoir', false, 'imperatif', '', 'demande', '', 'demandons', 'demandez', ''),
	('croire', 'avoir', false, 'passe_compose', 'ai cru', 'as cru', 'a cru', 'avons cru', 'avez cru', 'ont cru'),
	('prendre', 'avoir', false, 'present', 'prends', 'prends', 'prend', 'prenons', 'prenez', 'prennent'),
	('faire', 'avoir', false, 'imparfait', 'faisais', 'faisais', 'faisait', 'faisions', 'faisiez', 'faisaient'),
	('attendre', 'avoir', false, 'present', 'attends', 'attends', 'attend', 'attendons', 'attendez', 'attendent'),
	('prendre', 'avoir', false, 'imparfait', 'prenais', 'prenais', 'prenait', 'prenions', 'preniez', 'prenaient'),
	('manger', 'avoir', false, 'imparfait', 'mangeais', 'mangeais', 'mangeait', 'mangions', 'mangiez', 'mangeaient'),
	('enseigner', 'avoir', false, 'subjonctif', 'enseigne', 'enseignent', 'enseigne', 'enseignions', 'enseigniez', 'enseignent'),
	('comprendre', 'avoir', false, 'imperatif', '', 'comprends', '', 'comprenons', 'comprenez', ''),
	('montrer', 'avoir', false, 'subjonctif', 'montre', 'montres', 'montre', 'montrions', 'montriez', 'montrent'),
	('entendre', 'avoir', false, 'present', 'entends', 'entends', 'entend', 'entendons', 'entendez', 'entendent'),
	('devenir', 'être', false, 'imperatif', '', 'deviens', '', 'devenons', 'devenez', ''),
	('permettre', 'avoir', false, 'imperatif', '', 'permets', '', 'permettons', 'permettez', ''),
	('arriver', 'être', false, 'subjonctif', 'arrive', 'arrives', 'arrive', 'arrivions', 'arriviez', 'arrivent'),
	('manger', 'avoir', false, 'imperatif', '', 'mange', '', 'mangeons', 'mangez', ''),
	('entendre', 'avoir', false, 'imparfait', 'entendais', 'entendais', 'entendait', 'entendions', 'entendiez', 'entendaient'),
	('descendre', 'être', false, 'imperatif', '', 'descends', '', 'descendons', 'descendez', ''),
	('entendre', 'avoir', false, 'subjonctif', 'entende', 'entendes', 'entende', 'entendions', 'entendiez', 'entendent'),
	('ressembler', 'avoir', false, 'future_simple', 'ressemblerai', 'ressembles', 'ressemblera', 'ressemblerons', 'ressembrez', 'ressembleront'),
	('rire', 'avoir', false, 'future_simple', 'rirai', 'riras', 'rira', 'rirons', 'rirez', 'riront'),
	('rester', 'être', false, 'present', 'reste', 'restes', 'reste', 'restons', 'restez', 'restent'),
	('rester', 'être', false, 'subjonctif', 'reste', 'restes', 'reste', 'restions', 'restiez', 'restent'),
	('réussir', 'avoir', false, 'present', 'réussis', 'réussis', 'réussit', 'réussissons', 'réussissez', 'réussissent'),
	('réussir', 'avoir', false, 'subjonctif', 'réussisse', 'réussisses', 'réussisse', 'réussissions', 'réussissiez', 'réussissent'),
	('se sentir', 'être', true, 'present', 'me sens', 'te sens', 'se sent', 'nous sentons', 'vous sentez', 'se sentent'),
	('se sentir', 'être', true, 'subjonctif', 'que je me sente', 'que tu te sentes', 'qu''il/elle se sente', 'que nous nous sentions', 'que vous vous sentiez', 'qu''ils/elles se sentent'),
	('regarder', 'avoir', false, 'present', 'regarde', 'regardes', 'regarde', 'regardons', 'regardez', 'regardent'),
	('tenir', 'avoir', false, 'subjonctif', 'tienne', 'tiennes', 'tienne', 'tenions', 'teniez', 'tiennent'),
	('s''habiller', 'être', true, 'imparfait', 'me habillais', 'te habillais', 'se habillait', 'nous habillions', 'vous habilliez', 'se habillaient'),
	('vivre', 'avoir', false, 'imparfait', 'vivais', 'vivais', 'vivait', 'vivions', 'viviez', 'vivaient'),
	('tomber', 'être', false, 'conditionnel', 'tomberais', 'tomberais', 'tomberait', 'tomberions', 'tomberiez', 'tomberaient'),
	('vouloir', 'avoir', false, 'imparfait', 'voulais', 'voulais', 'voulait', 'voulions', 'vouliez', 'voulaient'),
	('vouloir', 'avoir', false, 'imperatif', '', 'veut', '', 'voulons', 'voulez', ''),
	('sortir', 'être', false, 'present', 'sors', 'sors', 'sort', 'sortons', 'sortez', 'sortent'),
	('s''appeler', 'être', true, 'imperatif', '', 'appelle-toi', '', 'appelons-nous', 'appelez-vous', ''),
	('s''asseoir', 'être', true, 'imparfait', 'm''asseyais', 't''asseyais', 's''asseyait', 'nous asseyions', 'vous asseyiez', 's''asseyaient'),
	('voir', 'avoir', false, 'present', 'vois', 'vois', 'voit', 'voyons', 'voyez', 'voient'),
	('vendre', 'avoir', false, 'conditionnel', 'vendrais', 'vendrais', 'vendrait', 'vendrions', 'vendriez', 'vendraient'),
	('trouver', 'avoir', false, 'conditionnel', 'trouverais', 'trouverais', 'trouverait', 'trouverions', 'trouveriez', 'trouveraient'),
	('servir', 'avoir', false, 'conditionnel', 'servirais', 'servirais', 'servirait', 'servirions', 'serviriez', 'serviraient'),
	('suivre', 'avoir', false, 'conditionnel', 'suivrais', 'suivrais', 'suivrait', 'suivrions', 'suivriez', 'suivraient'),
	('se laver', 'être', true, 'passe_compose', 'me suis lavé(e)', 't''es lavé(e)', 's''est lavé(e)', 'nous nous sommes lavé(e)s', 'vous vous êtes lavé(e)s', 'se sont lavé(e)s'),
	('se laver', 'être', true, 'imperatif', '', 'lave-toi', '', 'lavons-nous', 'lavez-vous', ''),
	('travailler', 'avoir', false, 'conditionnel', 'travaillerais', 'travaillerais', 'travaillerait', 'travaillerions', 'travailleriez', 'travailleraient'),
	('se souvenir', 'être', true, 'passe_compose', 'me suis souvenu', 't''es souvenu', 's''est souvenu', 'nous sommes souvenus', 'vous êtes souvenus', 'se sont souvenus'),
	('se souvenir', 'être', true, 'imperatif', '', 'souviens-toi', '', 'souvenons-nous', 'souvenez-vous', ''),
	('sentir', 'avoir', false, 'passe_compose', 'ai senti', 'as senti', 'a senti', 'avons senti', 'avez senti', 'ont senti'),
	('sentir', 'avoir', false, 'imperatif', '', 'sens', '', 'sentons', 'sentez', '')
ON CONFLICT (infinitive, auxiliary, reflexive, tense)
DO UPDATE SET
	first_person_singular = EXCLUDED.first_person_singular,
	second_person_singular = EXCLUDED.second_person_singular,
	third_person_singular = EXCLUDED.third_person_singular,
	first_person_plural = EXCLUDED.first_person_plural,
	second_person_plural = EXCLUDED.second_person_plural,
	third_person_plural = EXCLUDED.third_person_plural,
	updated_at = now();
